"""empty message

Revision ID: 0c3e8d2e312e
Revises: c749d91f5284
Create Date: 2018-09-26 19:57:20.675176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c3e8d2e312e'
down_revision = 'c749d91f5284'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('relpies', sa.Column('reply_name', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('relpies', 'reply_name')
    # ### end Alembic commands ###
