"""empty message

Revision ID: 6513dd780993
Revises: 6cf043866866
Create Date: 2018-11-08 04:59:56.853150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6513dd780993'
down_revision = '6cf043866866'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photos', sa.Column('cover', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('photos', 'cover')
    # ### end Alembic commands ###
