"""剪裁图片尺寸

Revision ID: 6cf043866866
Revises: 2ea459f2acf6
Create Date: 2018-11-07 23:22:57.781840

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6cf043866866'
down_revision = '2ea459f2acf6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photos', sa.Column('filename_m', sa.String(length=64), nullable=True))
    op.add_column('photos', sa.Column('filename_s', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('photos', 'filename_s')
    op.drop_column('photos', 'filename_m')
    # ### end Alembic commands ###
