"""empty message

Revision ID: c3970dc31dc7
Revises: 
Create Date: 2018-10-25 17:20:25.727911

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3970dc31dc7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('relpies', sa.Column('message_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'relpies', 'messages', ['message_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'relpies', type_='foreignkey')
    op.drop_column('relpies', 'message_id')
    # ### end Alembic commands ###
