"""empty message

Revision ID: c9f60c71feec
Revises: 0c3e8d2e312e
Create Date: 2018-09-30 21:51:40.077274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9f60c71feec'
down_revision = '0c3e8d2e312e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('relpies', sa.Column('replyto_id', sa.Integer(), nullable=True))
    op.add_column('relpies', sa.Column('replyto_uid', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'relpies', 'users', ['replyto_uid'], ['id'])
    op.drop_column('relpies', 'reply_id')
    op.drop_column('relpies', 'reply_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('relpies', sa.Column('reply_name', sa.VARCHAR(length=64), nullable=True))
    op.add_column('relpies', sa.Column('reply_id', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'relpies', type_='foreignkey')
    op.drop_column('relpies', 'replyto_uid')
    op.drop_column('relpies', 'replyto_id')
    # ### end Alembic commands ###
